[book]
authors = ["Juan Manuel Parrilla Madrid"]
language = "en"
multilingual = false
src = "topics"
title = "Utilitips"

[build]
build-dir = "public"

[output.html]
theme = "Coal"
default-theme = "Coal"
preferred-dark-theme = "Coal"
curly-quotes = true
